In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pyvista
import ufl
import time
from mpi4py import MPI
from petsc4py import PETSc
import dolfinx
from dolfinx import fem, mesh, plot, nls, log, io
from dolfinx import cpp as _cpp
import meshio
import os
import sys

sys.path.append('../')
%load_ext autoreload
%autoreload 2

print(dolfinx.__version__)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
0.7.2


In [2]:
from src.utils import *
from src.model import *

In [3]:
# Slab domain (single capillary)
vertex = [120,8,8]
num_nodes = [60,8,8]
domain = mesh.create_box(MPI.COMM_WORLD, [[0.0, 0.0, 0.0], vertex], num_nodes, mesh.CellType.tetrahedron) 

In [4]:
# plot_mesh(domain)

In [5]:
results_folder = r"../../results-data/"
exp_folder = "slab_test"

In [6]:
model = PerfusionGasExchangeModel(mesh_path=None,
                                  results_path=results_folder,
                                  exp_path=exp_folder,
                                  params=None)

In [7]:
model.Setup(domain, max_dims = vertex)
model.parameter_setup()

max_dims = [120, 8, 8]
min_dims = [0, 0, 0]
Total number = 4096
Inlet number = 128
Outlet number = 128
Air number = 3840


In [8]:
area = calculate_area(domain, model.ds, 3)
area

3840.000000000454

In [9]:
p, u = model.Perfusion(domain, plot=True, save=True)

Problem instanced.
Pressure field found.


Widget(value="<iframe src='http://localhost:34103/index.html?ui=P_0x7fd974ad63b0_0&reconnect=auto' style='widt…

Widget(value="<iframe src='http://localhost:34103/index.html?ui=P_0x7fd974ad6380_0&reconnect=auto' style='widt…

In [10]:
model.results_path

'../../results-data/slab_test'

In [11]:
p_val = 0
guess = model.GasExchange(domain, guess=None, save=False, 
                          plot=False, p_val = p_val, 
                          postprocess=False, plot_lines=False)
N = 4
for i in range(N):
    p_val += 1/N
    if i != N-1:
        guess = model.GasExchange(domain, guess=guess, save=False, 
                                  plot=False, p_val = p_val, 
                                  postprocess=False, plot_lines=False)
    else:
        guess = model.GasExchange(domain, guess=guess, save=False, 
                                  plot=True, p_val = p_val, 
                                  postprocess=True, plot_lines=False)

Finite element is CG


2024-04-07 15:35:19.627 (  12.897s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:19.783 (  13.053s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:19.844 (  13.114s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 2: r (abs) = 4.1025e-12 (tol = 1e-08) r (rel) = 5.46291e-16(tol = 1e-08)
2024-04-07 15:35:19.844 (  13.114s) [main            ]       NewtonSolver.cpp:255   INFO| Newton solver finished in 2 iterations and 2 linear solver iterations.


Problem solved in 2 iterations.
Finite element is CG
Starting nonlinear problem with previous guess.
p_val = 0.25


2024-04-07 15:35:20.552 (  13.821s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:21.241 (  14.510s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:21.416 (  14.686s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 2: r (abs) = 108.192 (tol = 1e-08) r (rel) = 0.210829(tol = 1e-08)
2024-04-07 15:35:21.888 (  15.157s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:22.059 (  15.329s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 3: r (abs) = 45.9292 (tol = 1e-08) r (rel) = 0.0895002(tol = 1e-08)
2024-04-07 15:35:22.543 (  15.812s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:22.712 (  15.981s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 

Problem solved in 7 iterations.
Finite element is CG
Starting nonlinear problem with previous guess.
p_val = 0.5


2024-04-07 15:35:25.403 (  18.673s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:26.091 (  19.360s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:26.255 (  19.525s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 2: r (abs) = 17.1968 (tol = 1e-08) r (rel) = 0.0947052(tol = 1e-08)
2024-04-07 15:35:26.724 (  19.994s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:26.904 (  20.173s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 3: r (abs) = 0.51495 (tol = 1e-08) r (rel) = 0.0028359(tol = 1e-08)
2024-04-07 15:35:27.413 (  20.682s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:27.581 (  20.851s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration

Problem solved in 5 iterations.
Finite element is CG
Starting nonlinear problem with previous guess.
p_val = 0.75


2024-04-07 15:35:28.973 (  22.242s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:29.661 (  22.931s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:29.833 (  23.102s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 2: r (abs) = 8.2552 (tol = 1e-08) r (rel) = 0.0622321(tol = 1e-08)
2024-04-07 15:35:30.305 (  23.574s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:30.469 (  23.739s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 3: r (abs) = 0.0960628 (tol = 1e-08) r (rel) = 0.000724173(tol = 1e-08)
2024-04-07 15:35:30.946 (  24.216s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:31.113 (  24.382s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iterat

Problem solved in 5 iterations.
Finite element is CG
Starting nonlinear problem with previous guess.
p_val = 1.0


2024-04-07 15:35:32.579 (  25.849s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:33.402 (  26.672s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:33.656 (  26.926s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 2: r (abs) = 5.22716 (tol = 1e-08) r (rel) = 0.0476907(tol = 1e-08)
2024-04-07 15:35:34.240 (  27.510s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:34.414 (  27.683s) [main            ]       NewtonSolver.cpp:36    INFO| Newton iteration 3: r (abs) = 0.0312206 (tol = 1e-08) r (rel) = 0.000284845(tol = 1e-08)
2024-04-07 15:35:34.921 (  28.190s) [main            ]              petsc.cpp:698   INFO| PETSc Krylov solver starting to solve system.
2024-04-07 15:35:35.096 (  28.366s) [main            ]       NewtonSolver.cpp:36    INFO| Newton itera

Problem solved in 5 iterations.
Starting postprocessing.
Finished postprocessing at t = 1.7742400169372559 s.


In [12]:
flux_in = calculate_flux(domain, model.ds, 1, fem.Constant(domain, dolfinx.default_real_type(1.0)), model.u, model.n)
print(f"flux in = {flux_in}")

flux_out = calculate_flux(domain, model.ds, 2, fem.Constant(domain, dolfinx.default_real_type(1.0)), model.u, model.n)
print(f"flux out = {flux_out}")

flux in = -10239.99877917807
flux out = 10239.988328932688


In [13]:
term1 = calculate_integral_over_domain(domain, model.dx, ufl.inner(model.u, ufl.grad(model.c_O2)))
term1 = term1 * 60 * 22400 / (model.t_params['p_O2_air'] - model.t_params['p_O2_in']) 
term1

AttributeError: 'PerfusionGasExchangeModel' object has no attribute 'c_O2'

In [ ]:
model.t_params['d_pla_O2']

1620.0

In [ ]:
term2 = calculate_integral_over_domain(domain, model.dx, -model.t_params['d_pla_O2']*ufl.div(ufl.grad(model.c_O2)))
term2

0.0

In [ ]:
u = calculate_integral_over_surface(domain, model.ds, [1,2,3], ufl.inner(-1*model.t_params['d_pla_O2']*ufl.grad(model.c_O2), model.n))
u

-9.990850430567725e-12

In [14]:
area = calculate_area(domain, model.ds, 1)
print(area)
flux_ref_in = area * model.p_params["uin"]
print(f"flux_ref_in = {flux_ref_in}")

63.99999999999963
flux_ref_in = 10239.999999999942


In [ ]:
# Filter out ghosted cells
num_cells_local = mesh.locate_entities_boundary(domain, fdim, all)
print(f"num_cells_local = {num_cells_local}")
marker = np.zeros(np.max(num_cells_local)+1, dtype=np.int32) 
# marker[right_facets] = 1
# marker[left_facets] = 2
# marker[top_facets] = 3
# marker[bottom_facets] = 4
marker[front_facets] = 5
marker[back_facets] = 10
marker[air_facets] = 0

topology, cell_types, x = dolfinx.plot.vtk_mesh(domain, fdim, np.arange(np.max(num_cells_local)+1, dtype=np.int32))

p = pyvista.Plotter(window_size=[800, 800])
grid = pyvista.UnstructuredGrid(topology, cell_types, x)
grid.cell_data["Marker"] = marker
grid.set_active_scalars("Marker")
p.add_mesh(grid, show_edges=True)
if pyvista.OFF_SCREEN:
    figure = p.screenshot("subdomains_structured.png")
p.show()

num_cells_local = [    0     2     4 ... 48125 48126 48127]


Widget(value="<iframe src='http://localhost:34871/index.html?ui=P_0x7f33daf8d390_0&reconnect=auto' style='widt…

In [ ]:
air_facets.shape

(3712,)

In [ ]:
facet_tag.find(6)

array([44596, 44597, 44598, 44824, 44825, 45019, 45026, 45027, 45057,
       45058, 45360, 45361, 45374, 45375, 45570, 45571, 45584, 45585,
       45746, 45753, 45754, 45808, 45809, 45866, 45867, 46048, 46049,
       46076, 46077, 46114, 46115, 46229, 46230, 46257, 46258, 46295,
       46379, 46386, 46387, 46441, 46442, 46513, 46514, 46635, 46636,
       46663, 46664, 46719, 46787, 46788, 46815, 46816, 46912, 46919,
       46920, 46974, 46975, 47024, 47025, 47122, 47123, 47150, 47151,
       47194, 47246, 47247, 47274, 47275, 47347, 47354, 47355, 47404,
       47405, 47437, 47438, 47511, 47512, 47539, 47540, 47571, 47607,
       47608, 47635, 47636, 47684, 47691, 47692, 47724, 47725, 47752,
       47753, 47802, 47803, 47823, 47824, 47850, 47870, 47871, 47891,
       47892, 47923, 47930, 47931, 47941, 47942, 47962, 47963, 47995,
       47996, 48004, 48005, 48024, 48035, 48036, 48044, 48045, 48065,
       48066, 48074, 48075, 48095, 48096, 48103, 48110, 48111, 48119,
       48120, 48127]

In [ ]:
facet_tag.find(7)

array([   23,    27,    32, ..., 48091, 48092, 48104], dtype=int32)

In [ ]:
p_O2_in = 40                   # mmHg
front_dofs_O2 = fem.locate_dofs_topological(V.sub(0), model.facet_tag.dim, model.facet_tag.find(5)) # Gamma_in
bc_O2 = fem.dirichletbc(dolfinx.default_scalar_type(p_O2_in), front_dofs_O2, V.sub(0))

In [ ]:
front_dofs_O2

array([   0,    1,    2,   10,   12,   20,   22,   28,   32,   34,   42,
         46,   48,   62,   66,   68,   76,   82,   86,   88,   96,  104,
        108,  110,  128,  136,  140,  148,  154,  162,  172,  180,  188,
        210,  218,  224,  236,  242,  250,  264,  274,  282,  310,  320,
        326,  340,  348,  358,  376,  386,  394,  430,  440,  446,  464,
        474,  484,  504,  518,  524,  566,  578,  584,  606,  616,  628,
        652,  666,  672,  722,  734,  740,  776,  788,  828,  834,  898,
        904,  954, 1000, 1070], dtype=int32)

In [ ]:
front_dofs_CO2 = fem.locate_dofs_topological(V.sub(1), model.facet_tag.dim, model.facet_tag.find(5))

In [ ]:
front_dofs_CO2

array([   4,    5,    6,   11,   14,   21,   24,   29,   33,   36,   43,
         47,   50,   63,   67,   70,   77,   83,   87,   90,   97,  105,
        109,  112,  129,  137,  141,  149,  155,  163,  173,  181,  189,
        211,  219,  225,  237,  243,  251,  265,  275,  283,  311,  321,
        327,  341,  349,  359,  377,  387,  395,  431,  441,  447,  465,
        475,  485,  505,  519,  525,  567,  579,  585,  607,  617,  629,
        653,  667,  673,  723,  735,  741,  777,  789,  829,  835,  899,
        905,  955, 1001, 1071], dtype=int32)

In [ ]:
W = fem.FunctionSpace(domain, ("Lagrange", 1))

In [ ]:
# f1 = fem.Function(W)
# f2 = fem.Function(W)
# f1mf2 = fem.Expression(f1-f2, W.element.interpolation_points())

p_XY = fem.Function(V)

In [ ]:
alpha_CO2 = fem.Constant(domain, dolfinx.default_scalar_type(3.27E-5))             # M mmHg^-1
alpha_O2 = fem.Constant(domain, dolfinx.default_scalar_type(1.46E-6))              # M mmHg^-1

K2p = fem.Constant(domain, dolfinx.default_scalar_type(21.5))                      # M^-1
K2pp = fem.Constant(domain, dolfinx.default_scalar_type(1E-6))                     # M
K3p = fem.Constant(domain, dolfinx.default_scalar_type(11.3))                      # M^-1
K3pp = fem.Constant(domain, dolfinx.default_scalar_type(1E-6))                     # M
K5pp = fem.Constant(domain, dolfinx.default_scalar_type(2.63E-8))                  # M
K6pp = fem.Constant(domain, dolfinx.default_scalar_type(1.91E-8))                  # M

# Red blood cell pH (with pH_plasma = 7.4).
pH_rbc = 7.24
c_H = fem.Constant(domain, dolfinx.default_scalar_type(10**(-pH_rbc)))

# Variables defined in Dash & Bassingthwaighte (2016).

phi_1 = fem.Constant(domain, dolfinx.default_scalar_type(1 + (K2pp/c_H)))
phi_2 = fem.Constant(domain, dolfinx.default_scalar_type(1 + (K3pp/c_H)))
phi_3 = fem.Constant(domain, dolfinx.default_scalar_type(1 + (c_H/K5pp)))
phi_4 = fem.Constant(domain, dolfinx.default_scalar_type(1 + (c_H/K6pp)))